export const FETCHING_TRACK = 'FETCHING_TRACK'
export const FETCHING_TRACK_SUCCESS = 'FETCHING_TRACK_SUCCESS'
export const FETCHING_TRACK_FAILURE = 'FETCHING_TRACK_FAILURE'
export const CHANGE_ROUTER = 'CHANGE_ROUTER'
